version: '3'
services:
  node-app:
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      
  redis:
    image: redis
      
volumes:
  mysql-db: